[package]
name = "redditlang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorize = "0.1.0"
enquote = "1.1.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm15-0"] }
llvm-sys = "150.0.7"
pest = "2.6.1"
pest_derive = "2.6.1"
